import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, LogOut, PackageCheck, Save, Star, UserRound, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { getAccount, supabase, updateAccount, type AccountData } from "@/lib/supabase";
import { useStoreData } from "@/contexts/StoreDataContext";

const brl = (value: number) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function Account() {
  const [, navigate] = useLocation(); const { user } = useStoreData();
  const [data, setData] = useState<AccountData | null>(null); const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({ name: "", phone: "", email: "", address: "" });
  useEffect(() => { if (!user) { navigate("/entrar"); return; } getAccount().then((result) => { setData(result); setForm({ name: result.customer?.name || result.profile.full_name || "", phone: result.customer?.phone || result.profile.phone || "", email: result.customer?.email || result.profile.email || user.email || "", address: result.customer?.address || "" }); }).catch((error) => toast.error(error.message || "Não foi possível carregar sua conta.")).finally(() => setLoading(false)); }, [user]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const result = await updateAccount(form); setData(result); toast.success("Perfil atualizado."); } catch (error: any) { toast.error(error.message || "Falha ao salvar o perfil."); } };
  const logout = async () => { await supabase.auth.signOut(); navigate("/"); };
  if (loading) return <main className="account-page"><div className="shell account-loading">Carregando sua conta...</div></main>;
  if (!data) return null;
  return <main className="account-page"><section className="shell account-shell"><button className="back-link" onClick={() => navigate("/")}><ArrowLeft size={15} /> Voltar à loja</button><div className="account-heading"><div><p className="eyebrow">Minha conta</p><h1>Olá, {(form.name || "Cliente").split(" ")[0]}</h1><p>Seus dados e pedidos ficam reunidos aqui.</p></div><button className="outline-button account-logout" onClick={logout}><LogOut size={16} /> Sair</button></div><div className="account-stats"><article><Star size={19} /><span>Pontos</span><strong>{data.customer?.points || 0}</strong></article><article><PackageCheck size={19} /><span>Pedidos</span><strong>{data.customer?.orders_count || data.orders.length}</strong></article><article><WalletCards size={19} /><span>Total gasto</span><strong>{brl(data.customer?.total_spent || 0)}</strong></article></div><div className="account-grid"><section className="account-panel"><div className="account-panel__head"><UserRound size={19} /><div><h2>Meu perfil</h2><p>Dados usados no atendimento e na entrega.</p></div></div><form className="profile-form" onSubmit={submit}><label>Nome completo<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><div className="profile-row"><label>WhatsApp<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /></label><label>E-mail<input value={form.email} type="email" disabled /></label></div><label>Endereço principal<input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Rua, número, bairro e cidade" /></label><button className="primary-button"><Save size={16} /> Salvar alterações</button></form></section><section className="account-panel orders-panel"><div className="account-panel__head"><PackageCheck size={19} /><div><h2>Meus pedidos</h2><p>Acompanhe o andamento das suas compras.</p></div></div><div className="account-orders">{data.orders.length ? data.orders.map((order: any) => <article key={order.id}><div><strong>{order.order_number ? `NF-${String(order.order_number).padStart(6, "0")}` : "Pedido"}</strong><small>{new Date(order.created_at).toLocaleDateString("pt-BR")}</small></div><span className={`order-state order-state--${String(order.status).toLowerCase()}`}>{String(order.status).replaceAll("_", " ")}</span><b>{brl(order.total)}</b></article>) : <div className="account-empty"><PackageCheck size={30} /><p>Você ainda não possui pedidos registrados.</p><button className="text-link" onClick={() => navigate("/produtos")}>Ver produtos</button></div>}</div></section></div></section></main>;
}
