-- Natal Farma V4 — base de produção Supabase/PostgreSQL
-- Execute no SQL Editor do projeto Supabase. Depois crie o primeiro usuário no Auth
-- e defina profiles.role = 'admin' manualmente para esse usuário.
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text, role text not null default 'customer' check(role in('customer','staff','admin')), created_at timestamptz not null default now());
create table if not exists public.products(id bigint generated by default as identity primary key,name text not null,category text not null,description text default '',price numeric(12,2) not null check(price>=0),cost numeric(12,2) not null default 0 check(cost>=0),stock integer not null default 0 check(stock>=0),min_stock integer not null default 0 check(min_stock>=0),expiry date,image_url text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.customers(id uuid primary key default gen_random_uuid(),auth_user_id uuid unique references auth.users(id) on delete set null,name text not null,phone text not null unique,email text,address text,total_spent numeric(12,2) not null default 0,orders_count integer not null default 0,points integer not null default 0,last_order_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.delivery_zones(id bigint generated by default as identity primary key,name text not null,fee numeric(12,2) not null default 0 check(fee>=0),active boolean not null default true);
create table if not exists public.coupons(id bigint generated by default as identity primary key,code text not null unique,type text not null check(type in('percent','fixed')),value numeric(12,2) not null check(value>=0),min_total numeric(12,2) not null default 0,expires date,active boolean not null default true);
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),number bigint generated by default as identity unique,customer_id uuid references public.customers(id),customer_name text not null,customer_phone text not null,customer_email text,customer_address text not null,subtotal numeric(12,2) not null,discount numeric(12,2) not null default 0,delivery_fee numeric(12,2) not null default 0,total numeric(12,2) not null,payment_method text not null,payment_status text not null default 'Pendente',order_status text not null default 'Novo',delivery_type text not null default 'Entrega',delivery_zone text,coupon_code text,cancel_reason text,stock_applied boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_items(id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,product_id bigint references public.products(id),name text not null,unit_price numeric(12,2) not null,unit_cost numeric(12,2) not null default 0,quantity integer not null check(quantity>0));
create table if not exists public.order_audit(id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,actor_id uuid references auth.users(id),actor_name text not null,event text not null,created_at timestamptz not null default now());
create table if not exists public.loyalty_transactions(id bigint generated by default as identity primary key,customer_id uuid not null references public.customers(id) on delete cascade,order_id uuid references public.orders(id),points integer not null,kind text not null check(kind in('earn','redeem','adjust')),description text,created_at timestamptz not null default now());
create table if not exists public.store_settings(id integer primary key default 1 check(id=1),whatsapp text,address text,hours_week text,hours_sunday text,banner_title text,banner_subtitle text,banner_button text,banner_link text,banner_image_url text,free_delivery_min numeric(12,2) not null default 0,loyalty_rate numeric(8,2) not null default 1,loyalty_redeem_points integer not null default 500,loyalty_redeem_value numeric(12,2) not null default 20,updated_at timestamptz not null default now());
insert into public.store_settings(id) values(1) on conflict do nothing;

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('staff','admin'))$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')$$;

alter table public.profiles enable row level security;alter table public.products enable row level security;alter table public.customers enable row level security;alter table public.delivery_zones enable row level security;alter table public.coupons enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.order_audit enable row level security;alter table public.loyalty_transactions enable row level security;alter table public.store_settings enable row level security;

create policy "public read active products" on public.products for select using(active=true or public.is_staff());
create policy "staff manage products" on public.products for all using(public.is_staff()) with check(public.is_staff());
create policy "public read active zones" on public.delivery_zones for select using(active=true or public.is_staff());
create policy "staff manage zones" on public.delivery_zones for all using(public.is_staff()) with check(public.is_staff());
create policy "staff manage coupons" on public.coupons for all using(public.is_staff()) with check(public.is_staff());
create policy "public read valid coupons" on public.coupons for select using(active=true and (expires is null or expires>=current_date));
create policy "public read store settings" on public.store_settings for select using(true);
create policy "staff manage settings" on public.store_settings for all using(public.is_staff()) with check(public.is_staff());
create policy "own profile or staff" on public.profiles for select using(id=auth.uid() or public.is_staff());
create policy "admin manage profiles" on public.profiles for all using(public.is_admin()) with check(public.is_admin());
create policy "customer sees own row" on public.customers for select using(auth_user_id=auth.uid() or public.is_staff());
create policy "staff manage customers" on public.customers for all using(public.is_staff()) with check(public.is_staff());
create policy "customer sees own orders" on public.orders for select using(public.is_staff() or customer_id in(select id from public.customers where auth_user_id=auth.uid()));
create policy "staff manage orders" on public.orders for all using(public.is_staff()) with check(public.is_staff());
create policy "customer sees own order items" on public.order_items for select using(public.is_staff() or order_id in(select o.id from public.orders o join public.customers c on c.id=o.customer_id where c.auth_user_id=auth.uid()));
create policy "staff manage order items" on public.order_items for all using(public.is_staff()) with check(public.is_staff());
create policy "audit visible to staff or owner" on public.order_audit for select using(public.is_staff() or order_id in(select o.id from public.orders o join public.customers c on c.id=o.customer_id where c.auth_user_id=auth.uid()));
create policy "staff manage audit" on public.order_audit for all using(public.is_staff()) with check(public.is_staff());
create policy "loyalty own or staff" on public.loyalty_transactions for select using(public.is_staff() or customer_id in(select id from public.customers where auth_user_id=auth.uid()));
create policy "staff manage loyalty" on public.loyalty_transactions for all using(public.is_staff()) with check(public.is_staff());

-- Criação de pedido público validada no servidor. O cliente envia IDs/quantidades; preço real vem da tabela products.
create or replace function public.create_public_order(payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare oid uuid:=gen_random_uuid(); it jsonb; p public.products%rowtype; sub numeric:=0; disc numeric:=0; fee numeric:=greatest(coalesce((payload->>'delivery_fee')::numeric,0),0); totalv numeric; c public.coupons%rowtype; cid uuid; ph text:=regexp_replace(payload->>'phone','\\D','','g');
begin
 if length(trim(payload->>'name'))<2 or length(ph)<10 or length(trim(payload->>'address'))<5 then raise exception 'Dados do cliente inválidos'; end if;
 if jsonb_array_length(payload->'items')=0 then raise exception 'Carrinho vazio'; end if;
 foreach it in array select array_agg(value) from jsonb_array_elements(payload->'items') loop
  select * into p from public.products where id=(it->>'id')::bigint and active=true for update;
  if not found or (it->>'qty')::int<1 or p.stock<(it->>'qty')::int then raise exception 'Produto indisponível ou estoque insuficiente'; end if;
  sub:=sub+p.price*(it->>'qty')::int;
 end loop;
 if coalesce(payload->>'coupon','')<>'' then select * into c from public.coupons where upper(code)=upper(payload->>'coupon') and active=true and (expires is null or expires>=current_date) and min_total<=sub; if found then disc:=case when c.type='percent' then sub*c.value/100 else c.value end;disc:=least(disc,sub);end if; end if;
 select coalesce((select 0 from public.store_settings where free_delivery_min>0 and sub>=free_delivery_min limit 1),fee) into fee;
 totalv:=greatest(0,sub+fee-disc);
 insert into public.customers(name,phone,email,address,total_spent,orders_count,points,last_order_at) values(trim(payload->>'name'),ph,nullif(trim(payload->>'email'),''),trim(payload->>'address'),totalv,1,floor(sub*coalesce((select loyalty_rate from public.store_settings where id=1),1))::int,now()) on conflict(phone) do update set name=excluded.name,email=coalesce(excluded.email,public.customers.email),address=excluded.address,total_spent=public.customers.total_spent+excluded.total_spent,orders_count=public.customers.orders_count+1,points=public.customers.points+excluded.points,last_order_at=now() returning id into cid;
 insert into public.orders(id,customer_id,customer_name,customer_phone,customer_email,customer_address,subtotal,discount,delivery_fee,total,payment_method,delivery_type,delivery_zone,coupon_code) values(oid,cid,trim(payload->>'name'),ph,nullif(trim(payload->>'email'),''),trim(payload->>'address'),sub,disc,fee,totalv,payload->>'payment_method',coalesce(payload->>'delivery_type','Entrega'),payload->>'delivery_zone',nullif(payload->>'coupon',''));
 foreach it in array select array_agg(value) from jsonb_array_elements(payload->'items') loop select * into p from public.products where id=(it->>'id')::bigint;insert into public.order_items(order_id,product_id,name,unit_price,unit_cost,quantity) values(oid,p.id,p.name,p.price,p.cost,(it->>'qty')::int);end loop;
 insert into public.order_audit(order_id,actor_name,event) values(oid,'Cliente','Pedido criado pelo site');return oid;
end$$;
revoke all on function public.create_public_order(jsonb) from public;grant execute on function public.create_public_order(jsonb) to anon,authenticated;
